# Generated by Django 5.0.2 on 2024-02-12 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_music_config', '0002_alter_musiccontainer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccontainer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musiccontainer',
            name='genre',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='musiccontainer',
            name='sample_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='musiccontainer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
