# Generated by Django 5.0.2 on 2024-02-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_music_config', '0003_musiccontainer_created_musiccontainer_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccontainer',
            name='music_cover_art',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='music_files/cover_art'),
        ),
        migrations.AlterField(
            model_name='musiccontainer',
            name='music_file',
            field=models.FileField(upload_to='music_files/audio'),
        ),
    ]
