# Generated by Django 4.2.10 on 2024-02-20 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root_music_config', '0004_musiccontainer_music_cover_art_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccontainer',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_total_stream', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musiccontainer',
            name='music_cover_art',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='music_files/cover_art/'),
        ),
        migrations.AlterField(
            model_name='musiccontainer',
            name='music_file',
            field=models.FileField(upload_to='music_files/audio/'),
        ),
    ]
