# Generated by Django 5.0.2 on 2024-02-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_user', '0002_remove_authusermodel_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authusermodel',
            old_name='user_name',
            new_name='username',
        ),
    ]
