# Generated by Django 5.0.2 on 2024-02-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_user', '0005_alter_authusermodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authusermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
