# Generated by Django 4.2.10 on 2024-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_user', '0006_alter_authusermodel_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authusermodel',
            name='premium_user',
        ),
        migrations.AddField(
            model_name='authusermodel',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authusermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
